### ISSUE TITLE
Possible bug in miniexact_choose_i_mrv_slacker of algorithm.c

### ISSUE THREAD

**Issue by progbee** [miniexact/miniexact#1]
In this line:
https://github.com/miniexact/miniexact/blob/72105b34c725f1d23ed2fe80bc01480145515eae/src/algorithm.c#L363C1-L363C71
should SLACK(p_) == SLACK(i) be changed to SLACK(p_) < SLACK(i) instead?

**Comment by maximaximal** [comment]
You are absolutely right, I think I slipped up when reading and mixed in a different predicate. I hope this makes this software more usable for you and thank you very much for finding this bug!
